config/routes.rb
Rails.application.routes.draw do
  # get 'followers/create'
  # get 'followers/new'
  # get 'messages/create'
  # get 'messages/destroy'
  # get 'reviews/create'
  # get 'proposals/create'
  # get 'wishes/create'
  # get 'profiles/show'
  # get 'expos/index'
  # get 'expos/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :expos, only: %i[show index] do
    resources :wishes, only: :create
    resources :proposals, only: %i[create index show]
    resources :reviews, only: %i[new create]
  end

  resources :wishes, only: :destroy

  resources :proposals, only: :destroy do
    resources :messages, only: :create
    resources :participants, only: :create
  end

  resources :users, only: %i[show edit update index] do
    resources :followings, only: %i[create new]
    member do
      get :profile
    end
  end

  resources :messages, only: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :followings, dependent: :destroy
  has_many :followers, class_name: "Following", foreign_key: :receiver_id, dependent: :destroy


  has_many :messages, dependent: :destroy
  has_many :proposals, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :wishes, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :email, uniqueness: true
  has_one_attached :photo

  # Renvoie les proposals auxquelles je participe
  has_many :participations, through: :participants, source: :proposal


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    if params[:cookie].present?
      if params[:cookie] == "follow"
        follow = Following.new(user_id: current_user.id, receiver_id: params[:user])
        follow.save
      elsif params[:cookie] == "unfollow"
        current_user.followings.find_by(receiver_id: User.find(params[:user])).destroy
      end
    end
  end


  def profile
    @user = User.find(params[:id])
    @followings = @user.followings.includes(:user)
    @followers = @user.followers.includes(:user)
    @wishes = @user.wishes.includes(:expo)
    @reviews = @user.reviews.includes(:expo)
    @proposals = @user.participations.includes(:expo)

    if params[:cookie].present?
      if params[:cookie] == "follow"
        Following.new(user_id: current_user.id, receiver_id: @user.id).save
      elsif params[:cookie] == "unfollow"
        current_user.followings.find_by(receiver_id: @user.id).destroy
      end
    end
  end
end

app/views/users/index.html.erb
<div class="container-index-user">

    <% @users.each do |user| %>
      <div class="card-index-user d-flex my-3 align-items-center justify-content-between">
        <div class="d-flex align-items-center">
          <%= link_to profile_user_path(user) do %>
            <%= user.photo.attached? ? cl_image_tag(user.photo.key, height: 100, width: 100, :quality=>"auto", :fetch_format=>:auto, gravity:"faces" , :crop=>"fill", class: "avatar-large mx-1") : image_tag('black_placeholder.jpg', class: "avatar-large mx-1") %>
          <% end %>
          <h1 class="subtitle ms-2"><%= user.username %></h1>
        </div>
        <div class="d-flex align-items-center">
          <%= link_to profile_user_path(user) do %>
            <i class="fa-solid fa-eye voir-logo"></i>
          <% end %>
          <% if (current_user.followings.map {|e| e.receiver_id}).include?(user.id) %>

            <%= link_to users_path(params[:id], cookie: "unfollow", user: user.id)  do%>
              <!-- <i class="fa-solid fa-plug-circle-xmark logo-follow" style="font-size: 20px;"></i> -->
              <span class="material-symbols-outlined logo-follow">do_not_disturb_on</span>
            <% end %>

          <% else %>

            <%= link_to users_path(params[:id], cookie: "follow", user: user.id) do %>
              <!-- <i class="fa-solid fa-plug-circle-plus logo-follow" style="font-size: 20px;"></i> -->
              <span class="material-symbols-outlined logo-follow">person_add</span>
            <% end %>

          <% end %>

        </div>
      </div>
      <hr>
    <% end %>

</div>

app/views/users/profile.html.erb
<div class="container-profile">

  <!-- profile avatar -->
  <div class="d-flex justify-content-center align-items-center">

    <%= render "shared/avatar", user: @user, css_class: "avatar-xl" %>


    <% if user_signed_in? && @user == current_user %>
      <li class="list-inline-item dropup align-self-start button-top-profile">
        <i class="fa-solid fa-ellipsis-vertical dropdown profile-dropdown-icon" style="font-size: 25px;" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>

        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "LOG OUT", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          <%= link_to "EDIT", edit_user_registration_path, class: "dropdown-item" %>
        </div>
      </li>
    <% else %>
      <div class="button-top-profile">

       <% if (current_user.followings.map {|e| e.receiver_id}).include?(@user.id) %>

          <%= link_to profile_user_path(params[:id], cookie: "unfollow")  do%>
            <!-- <i class="fa-solid fa-plug-circle-xmark logo-follow" style="font-size: 20px;"></i> -->
            <span class="material-symbols-outlined logo-follow">do_not_disturb_on</span>
          <% end %>

        <% else %>

          <%= link_to profile_user_path(params[:id], cookie: "follow") do %>
            <!-- <i class="fa-solid fa-plug-circle-plus logo-follow" style="font-size: 20px;"></i> -->
            <span class="material-symbols-outlined logo-follow">person_add</span>
          <% end %>

        <% end %>

      </div>
    <% end %>
  </div>

  <div class="d-flex justify-content-center">
    <h1 class="review_title-small mb-0 mt-3"><%= @user.username %></h1>
  </div>

  <hr class="filet-profil">

  <!-- profile description -->
  <% if @user.description != nil %>
    <p class="paragraphe" style="text-align: center; font-size: 20px; line-height: 24px; margin-top: 1px; margin-bottom: 14px;"><%= @user.description %></p>
    <hr class="filet-profil">
  <% end %>

<!-- proposals -->
  <% if @proposals.count  > 0  %>
    <div class="d-flex justify-content-between">
      <h1 class="title mb-2">Sorties prévues</h1>
      <div class="notif subtitle sorties">
        <div class="text-notif"><%= @proposals.count %></div>
      </div>
    </div>
    <div class="profil-horizontal-scroll d-flex">
      <% @proposals.each do |proposal| %>
        <div class="card-small subtitle-bold "  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(proposal.expo.photo.key) %>">
          <p><%= link_to (l proposal.date_proposale, format: "%d %B %Y"), expo_proposal_path(proposal.expo, proposal) %></p>
        </div>
      <% end %>
    </div>
    <hr class="filet-profil">
  <% end %>


<!-- wishes -->
  <% if @wishes.count  > 0  %>
    <div class="d-flex justify-content-between">
      <h1 class="title mb-2">Favoris</h1>
      <div class="notif subtitle favoris">
         <div class="text-notif"><%= @wishes.count %></div>
      </div>
    </div>
    <div class="profil-horizontal-scroll d-flex mt-1">
      <% @wishes.each do |wish| %>
        <div class="card-small subtitle "  style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.1)), url(<%= cl_image_path(wish.expo.photo.key) %>">
          <p><%= link_to wish.expo.title.upcase, expo_path(wish.expo) %></p>
        </div>
      <% end %>
    </div>
    <hr class="filet-profil">
  <% end %>

  <!-- abonnements -->
  <% if @followings.count > 0 %>
    <div class="d-flex justify-content-between">
      <h1 class="title">Abonnements</h1>
      <div class="notif subtitle abonnements">
         <div class="text-notif"><%= @followings.count %></div>
      </div>
      <%= link_to users_path do%>
        <i class="fa-solid fa-plus bouton-abonnements" ></i>
      <% end %>
    </div>
    <div class="profil-horizontal-scroll d-flex mt-1">
      <% @followings.each do |following| %>
        <%= link_to profile_user_path(following.receiver) do %>
          <%= following.receiver.photo.attached? ? cl_image_tag(following.receiver.photo.key, class: "avatar-large mx-1") : image_tag('black_placeholder.jpg', class: "avatar-large mx-1") %>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="d-flex justify-content-between">
      <h1 class="title">Abonnements</h1>
      <%= link_to users_path do%>
        <i class="fa-solid fa-plus bouton-abonnements" ></i>
      <% end %>
    </div>
    <p class="paragraphe">Vous n'avez aucun abonnement. Retrouvez vos amis avec le bouton +</p>

  <% end %>

  <!-- abonnés -->

  <!-- <div class="d-flex justify-content-between">
    <h1 class="title mb-2">Mes abonnés - <%= @followers.count %></h1>
  </div>
  <div class="horizontal-scroll d-flex">
    <% @followers.each do |follower| %>
      <%= follower.user.photo.attached? ? cl_image_tag(follower.user.photo.key, class: "avatar-large mx-1") : image_tag('black_placeholder.jpg', class: "avatar-large mx-1") %>
    <% end %>
  </div>
  <hr class="my-2">

</div> -->