config/routes.rb
Rails.application.routes.draw do
  # get 'followers/create'
  # get 'followers/new'
  # get 'messages/create'
  # get 'messages/destroy'
  # get 'reviews/create'
  # get 'proposals/create'
  # get 'wishes/create'
  # get 'profiles/show'
  # get 'expos/index'
  # get 'expos/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :expos, only: %i[show index] do
    resources :wishes, only: :create
    resources :proposals, only: %i[create index show]
    resources :reviews, only: %i[new create]
  end

  resources :wishes, only: :destroy

  resources :proposals, only: :destroy do
    resources :messages, only: :create
    resources :participants, only: :create
  end

  resources :users, only: %i[show edit update index] do
    resources :followings, only: %i[create new]
    member do
      get :profile
    end
  end

  resources :messages, only: :destroy
end

app/views/shared/_avatar.html.erb
  <% if user.photo.attached? %>
    <%= cl_image_tag(user.photo.key, height: 100, width: 100, :quality=>"auto", :fetch_format=>:auto, gravity:"faces" , :crop=>"fill", class: "avatar #{css_class}") %>
  <% else %>
    <%= image_tag "avatar_placeholder.png", class: "avatar #{css_class}" %>
  <% end %>

app/views/shared/_filter_tag.html.erb
<div class="d-flex align-items-center justify-content-center">
  <%= tag %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_form_proposal.html.erb
<div>
  <%= simple_form_for([@expo, @proposal], html: { data: { controller: "flatpickr" } }) do |f| %>
      <%= f.input :date_proposale, label: 'Date', as: :string, required: false, input_html: {class: 'datepicker'}, placeholder: 'Choississez la date', class: "proposal_title-small" %>
      <%= f.input :description, placeholder: 'Ajouter une déscription...', class: "proposal_title-small" %>
      <%= f.input :max_participants, label: 'nombre de participants', collection: 1..5, selected: 1, class: "proposal_popup"  %>
      <%= f.submit 'Créer', class: "proposal_action-button color", id:"submit-proposal"%>
    <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_message.html.erb
<% if message.user == current_user %>
  <div class="float-end" id="message<%= message.id %>" data-proposal-subscription-target="message">
    <div class="d-flex">
      <div class="pt-1 pe-2">
        <% if message.user.photo.attached? %>
          <%= cl_image_tag message.user.photo.key, class: "avatar" %>
        <% else %>
          <%= image_tag "avatar_placeholder.png", class: "avatar" %>
        <% end %>
      </div>
      <div>
        <small>
          <strong class="message-author"><%= message.user.username %></strong>
            <i id="chat-time"><%= message.created_at.strftime("%l:%M%p") %></i>
        </small>
        <p id="chat-message"><%= message.content %></p>
      </div>
    </div>
<% else %>
  <div class="float-start" id="message<%= message.id %>" data-proposal-subscription-target="message">
    <div class="d-flex">
      <div class="pt-1 pe-2">
        <% if message.user.photo.attached? %>
          <%= cl_image_tag message.user.photo.key, class: "avatar" %>
        <% else %>
          <%= image_tag "avatar_placeholder.png", class: "avatar" %>
        <% end %>
      </div>
      <div>
        <small>
          <strong class="message-author"><%= message.user.username %></strong>
            <i id="chat-time"><%= message.created_at.strftime("%l:%M%p") %></i>
        </small>
        <p><%= message.content %></p>
      </div>
    </div>
<% end %>
</div>

app/views/shared/_messages_proposal.html.erb
<%= simple_form_for [@proposal,@message], html: { data: { action: "turbo:submit-end->proposal-subscription#resetForm" }, class: "" } do |f| %>
  <%= f.input :content, label: false, placeholder: "Votre message...", wrapper_html: {class: "flex-grow-1"} %>
  <div class="button-container">
    <%= f.submit "Envoyer", class: "action-button subtitle" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container-navbar">
  <div class="navbar">
    <ul class="list-inline">
      <li class="list-inline-item">
        <%= link_to root_path, class: "navbar-icone" do %>
          <i class="fa-solid fa-house" style="font-size: 28px"></i>
        <% end %>
      </li>
      <li class="list-inline-item">
        <%= link_to expos_path(), class: "navbar-icone" do %>
          <i class="fa-solid fa-list-ul" style="font-size: 30px"></i>
        <% end %>
      </li>
      <li class="list-inline-item">
        <%= link_to expos_path({index: "map"}.merge(session[:all_filter_params] || {})), class: "navbar-icone" do %>
          <i class="fa-regular fa-map" style="font-size: 28px"></i>
        <% end %>
      </li>

          <% if user_signed_in? %>
            <%= link_to profile_user_path(current_user) do %>
              <%= render "shared/avatar", user: current_user, css_class: "avatar-bordered" %>
            <% end %>
          <% else %>
            <li class="list-inline-item dropup">
            <%= image_tag "avatar_placeholder.png", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "LOG IN", new_user_session_path, class: "dropdown-item" %>
                <%= link_to "SIGN UP", new_user_registration_path, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>

    </ul>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<div class="search-bar-container">

  <div class="search-bar-body">

    <%= simple_form_for :filters, url: expos_path, method: :get do |f| %>
      <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-search">
          <div class="modal-content">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

            <p class="title_modal">CATEGORIES</p>
            <div class="modal-question">
              <h5 class="modal-subtitle" id="exampleModalToggleLabel">QUEL TYPE D'EXPO CHERCHES-TU ?</h5>
              <hr>
            </div>
            <div class="modal-body min-height">
              <%= f.input :categories,
                collection: Expo.tags,
                as: :check_boxes,
                input_html: { class: "tag-selector" },
                item_wrapper_class: 'tag-item',
                label_method: lambda { |tag| render 'shared/filter_tag', tag: tag },
                include_hidden: false,
                checked: params.dig(:filters, :categories) %>
            </div>
            <div class="modal-footer">

              <div class="filter-button-container next-tag-container" id="next-tag-container">
                <button class="action-button next-tag" id="next-tag" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" type="button">
                  <p>SUIVANT</p>
                <!-- </button>
                <button type="button" class="action-button next-tag opacity-0" data-bs-toggle="modal" data-bs-target="#exampleModalToggle">
                  <p>BACK</p>
                </button> -->
              </div>
            </div>
          </div>
        </div>
      </div>



      <div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered modal-search">
          <div class="modal-content">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            <p class="title_modal">BUDGET</p>
            <div class="modal-question">
              <h5 class="modal-subtitle" id="exampleModalToggleLabel2">SOUHAITES-TU VOIR UNIQUEMENT LES EXPOSITIONS GRATUITES ?</h5>
              <hr>
            </div>

            <div class="modal-body">
              <%= f.input :price_type,
                  collection: ["GRATUITES", "PEU IMPORTE"],
                  as: :check_boxes,
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item',
                  label_method: lambda { |tag| render 'shared/filter_tag', tag: tag },
                  include_hidden: false,
                  checked: params.dig(:filters, :price_type) %>
            </div>
            <div class="modal-footer">

              <button class="action-button next-tag" id="next-tag" data-bs-target="#exampleModalToggle3" data-bs-toggle="modal" type="button">
                <p>SUIVANT</p>
              </button>
              <button type="button" class="action-button next-tag" data-bs-toggle="modal" data-bs-target="#exampleModalToggle">
                <p>RETOUR</p>
              </button>
            </div>
          </div>
        </div>
      </div>



      <%# <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Back to first</button> %>



      <div class="modal fade" id="exampleModalToggle3" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered modal-search ">
          <div class="modal-content">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            <p class="title_modal">ACCESSIBILITÉ</p>
            <div class="modal-question">
              <h5 class="modal-subtitle" id="exampleModalToggleLabel2">SOUHAITES-TU DES CRITÈRES D'ACCESSIBILITÉ PARTICULIERS ?</h5>
              <hr>
            </div>

            <div class="modal-body">
              <%= f.input :target,
                  collection: ["JEUNE PUBLIC", "MOBILITE REDUITE", "MALENTENDANT", "PEU IMPORTE"],
                  as: :check_boxes,
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item',
                  label_method: lambda { |tag| render 'shared/filter_tag', tag: tag },
                  include_hidden: false,
                  checked: params.dig(:filters, :target) %>
            </div>

            <div class="modal-footer">
              <%= f.submit "GO!", class:"action-button next-tag", style:"background-color-none" %>
              <button type="button" class="action-button next-tag" data-bs-toggle="modal" data-bs-target="#exampleModalToggle2">
                <p>RETOUR</p>
              </button>
              <%# <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Back to first</button> %>
            </div>
          </div>
        </div>
      </div>

    <% end %>

  <%# <a class="btn btn-primary" data-bs-toggle="modal" href="#exampleModalToggle" role="button">Picto filtre</a> %>

    <form id="search-bar" action="/expos">
        <div id="filter-icone">
          <a data-bs-toggle="modal" href="#exampleModalToggle" role="button"><i class="fa-solid fa-clipboard-list"></i></a>
        </div>
        <div class="submit-input">
          <button type="submit" id="search-icone">
            <i class="fa-solid fa-magnifying-glass"></i>
          </button>
      </div>
      <div class="input-field">
        <input id="search-input" type="text" class="form-control" placeholder="Trouver une exposition..." name="query">
      </div>
    </form>

  </div>
</div>