config/routes.rb
Rails.application.routes.draw do
  # get 'followers/create'
  # get 'followers/new'
  # get 'messages/create'
  # get 'messages/destroy'
  # get 'reviews/create'
  # get 'proposals/create'
  # get 'wishes/create'
  # get 'profiles/show'
  # get 'expos/index'
  # get 'expos/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :expos, only: %i[show index] do
    resources :wishes, only: :create
    resources :proposals, only: %i[create index show]
    resources :reviews, only: %i[new create]
  end

  resources :wishes, only: :destroy

  resources :proposals, only: :destroy do
    resources :messages, only: :create
    resources :participants, only: :create
  end

  resources :users, only: %i[show edit update index] do
    resources :followings, only: %i[create new]
    member do
      get :profile
    end
  end

  resources :messages, only: :destroy
end

app/models/expo.rb
class Expo < ApplicationRecord
  belongs_to :place
  has_many :reviews, dependent: :destroy
  has_many :wishes, dependent: :destroy
  has_many :proposals, dependent: :destroy
  has_many :users, through: :reviews

  validates :title, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true

  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :title, :tags, :price_type ],
    associated_against: {
      place: [ :address_name, :address_city, :address_zipcode ]
    },
    using: {
      tsearch: { prefix: true }
    }

  def average_rating
    reviews.average(:rating)
  end

  def self.tags
    pluck(:tags).flatten.uniq.sort
    # self.all.map(&:tags).tally
    self.all.map(&:tags).flatten.tally.sort_by { |k, v| v }.reverse.first(6).map(&:first)
  end
end

app/controllers/expos_controller.rb
class ExposController < ApplicationController
  before_action :set_expo, only: [:show]
  # skip_before_action :authenticate_user!, only: [:index, :show]bn

  def index
    # @expos = Expo.all
    # @expos = @expos.where(tags: params[:filters][:categories]) if params[:filters].present?

    ####
    # @tags = [params[:filters][:categories]]

    # @expos = @expos.map do |expo|
    #   expo unless (expo.tags & @tags).empty?
    # end
    ###
    # pour la search et les filtres on peut voir pour utiliser les formules ci-dessous mais en discuter avec Cyril si besoin car certaines ne fonctionneront pas forcément comme tel
    # ---------
    if params[:query].present? && params[:query] != nil
      # sql_query = <<~SQL
      #   expos.title ILIKE :mot
      #   OR expos.description ILIKE :mot
      # SQL
      # @expos = Expo.where(sql_query, mot: "%#{params[:query]}%")
      @expos = Expo.global_search(params["query"])
      @queries = @expos.all.map(&:tags).flatten

    elsif params[:filters].present?
      @expos = Expo.where("tags && ARRAY[?]::varchar[]", params[:filters][:categories])
      @queries = params[:filters][:categories]

      unless @queries
        @queries = ['Toutes les meilleures expos']
        @expos = Expo.all
      end
    elsif session[:current_expo_id].present?
      @expos = Expo.where(id: session[:current_expo_id])
    else
    # elsif params[:commit].present?
    # @expos = policy_scope(Expo.where('category ILIKE ?', "%#{params[:commit]}"))
    # else
    # @expos = policy_scope(Expo)
      @expos = Expo.all
      @queries = ['Toutes les meilleures expos']
    end
    # end
    @all_filter_params = all_filter_params
    session[:all_filter_params] = all_filter_params

    @markers = @expos.map do |expo|
      {
        lat: expo.place.lat,
        lng: expo.place.lon,
        info_window: render_to_string(partial: "info_window", locals: { expo: expo }),
        image_url: helpers.asset_url("pin_map.png"),
        id: expo.id
      }
    end
  end

  def show
    @review = Review.new()
    @reviews = @expo.reviews
    @proposals = @expo.proposals
    session[:current_expo_id] = @expo.id
  end

  def display_filters
    params[:query]
  end


  private

  def all_filter_params
    return {} unless params[:filters].present?

    {
      filters: params.require(:filters).permit(categories: [], price_type: []),
      query: params.permit(:query)
    }
  end

  def set_expo
    @expo = Expo.find(params[:id])
  end

end

app/views/expos/_info_window.html.erb
    <div class="card-map">

      <div class="image-box">

        <%= cl_image_tag(expo.photo.key, height: 100, width: 100, :quality=>"auto", :fetch_format=>:auto, gravity:"faces" , :crop=>"fill", class: "image-card-index") %>

        <%= link_to expo_path(expo) do %>
          <div class="img-gradient"></div>
        <% end %>

        <%= link_to expo_wishes_path(expo, user_id: current_user.id), 'data-turbo-method': :post do %>
          <i class="fa-solid fa-heart heart-icon-small <%= current_user.wishes.where(expo_id: expo.id).empty? ? "" : "wish" %>"></i>
        <% end %>

      </div>

        <div class="expo-detail">

        <h2 class="title"><%= expo.title  %></h2>

        <div class="d-flex justify-content-between">
          <p class="subtitle"><%= expo.place.address_name  %></p>
          <p class="subtitle arrondissement"><%= expo.place.address_city  %> <%= expo.place.address_zipcode.split(//).last(2).join %></p>
        </div>

        <p class="subtitle">Du <%= (l expo.date_start, format: "%d %B") %> au <%= (l expo.date_end, format: "%d %B %Y") %></p>

      </div>

    </div>

app/views/expos/_review.html.erb
  <%= link_to profile_user_path(review.user) do %>
  <div class="review_avatar">
    <% if review.user.photo.attached? %>
      <%= cl_image_tag review.user.photo.key, class: "avatar-xl" %>
    <% else %>
      <%= image_tag "avatar_placeholder.png", class: "avatar-xl" %>
    <% end %>
  </div>
<% end  %>
<div class="show_review flex-grow-1">
  <span class="review_title-small"><%= review.user.username%></span>
  <div class="d-flex justify-content-between">
    <span class="review_sub-small"><%=review.created_at.strftime("%d %B %Y")%></span>
    <span class="review_sub-small"><%=review.rating %><i class="fa-solid fa-star-of-life ms-1 color" style="font-size: 16px"></i></span>
  </div>
  <p class="review-paragraphe-small"><%=review.comment %></p>
</div>

app/views/expos/index.html.erb
<% if params[:index] == "map" %>
  <!-- map  -->
  <div class="map_style" style="width: 100%; height: calc(100vh - 132px) ;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <!-- modal map  -->
  <% @expos.each do |expo| %>
    <div id="modal-map">
      <div class="modal fade" id="expo-<%=expo.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <!-- <div class="modal-header">
            </div> -->
            <div class="modal-body">
              <div class="modal-card">
                <div class="card-map">
                  <div class="image-box">
                    <%= cl_image_tag(expo.photo.key, height: 180, width: 400, :quality=>"auto", :fetch_format=>:auto, gravity:"faces" , :crop=>"fill", class: "image-card-map") %>

                    <%= link_to expo_path(expo) do %>
                      <div class="img-gradient"></div>
                    <% end %>

                    <%= link_to expo_wishes_path(expo, user_id: current_user.id), 'data-turbo-method': :post do %>
                      <i class="fa-solid fa-bookmark heart-icon-small <%= current_user.wishes.where(expo_id: expo.id).empty? ? "" : "wish" %>"></i>
                    <% end %>

                    <i class="fa-solid fa-star-of-life star-icon-map"></i>
                    <p class="average_rating-map subtitle"> <%= expo.average_rating&.round(1) %></p>

                    <%# <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> %>

                    <i class="fa-solid fa-xmark i-close" data-bs-dismiss="modal" aria-label="Close"></i>
                  </div>
                </div>
                <div class="expo-detail">
                  <h2 class="title"><%= expo.title  %></h2>
                  <div class="place">
                    <p class="subtitle"><%= expo.place.address_name  %></p>
                    <p class="subtitle-arrondissement-map"><%= expo.place.address_city  %> <%= expo.place.address_zipcode.split(//).last(2).join %></p>
                  </div>
                  <p class="subtitle">Du <%= (l expo.date_start, format: "%d %B") %> au <%= (l expo.date_end, format: "%d %B %Y") %></p>
                </div>
              </div>
            </div>
            <!-- <div class="modal-footer">
            </div> -->
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else  %>
  <!-- index  -->
  <div class="container-index">
    <div class="tag-container">
    <% if @queries %>
      <% @queries.each do |query| %>
        <div class="tag-query subtitle"><%= query %></div>
      <% end %>
    <% end %>
    </div>
    <% @expos.each do |expo| %>
      <div class="card-index">
        <div class="image-box" data-controller="wishes" data-wishes-path-value="<%= expo_wishes_path(expo, user_id: current_user.id) %>"> <!-- controller -->
          <%= cl_image_tag(expo.photo.key, height: 292, width: 384, :quality=>"auto", :fetch_format=>:auto, gravity:"faces", :crop=>"fill", class: "image-card-index") %>
          <%= link_to expo_path(expo) do %>
            <div class="img-gradient"></div>
          <% end %>


          <!-- <%= link_to expo_wishes_path(expo, user_id: current_user.id), 'data-turbo-method': :post do %>

              <i class="fa-solid fa-heart heart-icon <%= current_user.wishes.where(expo_id: expo.id).empty? ? "" : "wish" %>" data-wishes-target="hearts" data-action="click->wishes#like" ></i>
            <% end %> -->

          <%= render "wishes/heart", wish: current_user.wishes.find_by(expo_id: expo.id) %>
          <i class="fa-solid fa-star-of-life star-icon-index"></i>

          <p class="average_rating-index subtitle"> <%= expo.average_rating&.round(1) %></p>
        </div>
        <div class="info-index">
          <%= link_to expo_path(expo), class: "text-decoration-none" do %>
            <h2 class="title"><%= expo.title  %></h2>
            <div class="d-flex justify-content-between">
              <p class="subtitle"><%= expo.place.address_name  %></p>
              <p class="subtitle arrondissement color"><%= expo.place.address_city  %> <%= expo.place.address_zipcode.split(//).last(2).join %></p>
            </div>
            <p class="subtitle">Du <%= (l expo.date_start, format: "%d %B") %> au <%= (l expo.date_end, format: "%d %B %Y") %></p>
            <div class="tag-container">
              <% expo.tags.each do |tag| %>
                <% if @queries.include?(tag) %>
                  <div class="tag-actif subtitle"><%= tag %></div>
                <% else %>
                  <div class="tag-expo subtitle"><%= tag %></div>
                <% end %>
              <% end %>
            </div>
          <% end %>
          <hr class="filet-line">
        </div>
      </div>
    <% end %>
  <% end  %>
</div>

app/views/expos/show.html.erb
  <%# <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <%@expo.photo.each_with_index do |expo, index| %>
        <%# <div class="carousel-item <%= 'active' if index.zero? %>
          <%# <p>hello</p>
          <%= link_to expo_path(expo) do %>
            <%# <%= cl_image_tag(expo.photo.key, height: '292px', quality: 50) %>
          <%# <% end %>
        <%# </div>
      <% end %>
    <%# </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div> %>



<div class="display-show " data-controller="insert-in-list" data-insert-in-list-position-value="beforeend">

  <div class="display-show image-box-show" data-controller="wishes" data-wishes-path-value="<%= expo_wishes_path(@expo, user_id: current_user.id) %>">
    <%=cl_image_tag(@expo.photo.key, height: 292, width: 368, :quality=>"auto", :fetch_format=>:auto, gravity:"faces" , :crop=>"fill")%>
    <i class="fa-solid fa-star-of-life star-icon-show"></i>
    <p class="average_rating subtitle pb-2"> <%= @expo.average_rating&.round(1) %></p>
    <%= render "wishes/heart", wish: current_user.wishes.find_by(expo_id: @expo.id) %>
  </div>

  <div class="container-show">

    <div class="card-show">

        <h2 class="title"><%= @expo.title %></h2>

      <div class="d-flex justify-content-between">
        <p class="subtitle"><%= @expo.place.address_name  %></p>
        <p class="subtitle arrondissement"><%= @expo.place.address_city  %> <%= @expo.place.address_zipcode.split(//).last(2).join %></p>
      </div>
      <p class="subtitle">Du <%= (l @expo.date_start, format: "%d %B") %> au <%= (l @expo.date_end, format: "%d %B %Y") %></p>
    </div>

    <div class="button-container">
      <div class="action-button">
        <%= link_to expo_proposals_path(@expo) do %>
          <p class="color">Trouver une sortie</p>
        <% end %>
      </div>
    </div>

    <div class="tag-container">
      <% @expo.tags.each do |tag| %>
        <div class="tag-expo-show subtitle"><%= tag %></div>
      <% end %>
    </div>

    <div class="paragraphe mt-3 mb-4" style="overflow: hidden;">
      <%= @expo.description.html_safe %>
    </div>


    <%= render "reviews/form", expo: @expo, review: @review %>
    <div class="button-container">
      <button type="button" class="action-button next-tag" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Laisser un commentaire
      </button>
    </div>

    <div class="review-container"  data-insert-in-list-target="items">
      <% @expo.reviews.each do |review| %>
        <div class="d-flex">
          <%= render 'review', review: review %>
        </div>
      <hr>
      <% end %>
    </div>

  </div>
</div>