config/routes.rb
Rails.application.routes.draw do
  # get 'followers/create'
  # get 'followers/new'
  # get 'messages/create'
  # get 'messages/destroy'
  # get 'reviews/create'
  # get 'proposals/create'
  # get 'wishes/create'
  # get 'profiles/show'
  # get 'expos/index'
  # get 'expos/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :expos, only: %i[show index] do
    resources :wishes, only: :create
    resources :proposals, only: %i[create index show]
    resources :reviews, only: %i[new create]
  end

  resources :wishes, only: :destroy

  resources :proposals, only: :destroy do
    resources :messages, only: :create
    resources :participants, only: :create
  end

  resources :users, only: %i[show edit update index] do
    resources :followings, only: %i[create new]
    member do
      get :profile
    end
  end

  resources :messages, only: :destroy
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def new
    @review = Review.new
    @expo = Expo.find(params[:expo_id])
  end

  def create
    @expo = Expo.find(params[:expo_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.expo = @expo

    respond_to do |format|
      if @review.save
        format.html { redirect_to expo_path(@expo) }
        format.json # Follow the classic Rails flow and look for a create.json view
      else
        format.html { render "expos/show", status: :unprocessable_entity }
        format.json # Follow the classic Rails flow and look for a create.json view
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def set_expo
    @expo = Expo.find(params[:expo_id])
  end
end

app/views/reviews/_form.html.erb
<%= simple_form_for([expo, review],
  data: {insert_in_list_target: "form",
  action: "submit->insert-in-list#send"
  }) do |f|
%>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      <%# <div class="modal-header"> %>
        <p class="title_modal">TON COMMENTAIRE</p>
        <div class="title-margin-left">
          <hr>
        </div>
        <%# <h5 class="modal-title" id="exampleModalLabel">TON COMMENTAIRE</h5> %>
      <%# </div> %>
      <div class="modal-body">
        <%= f.input :rating, collection: (1..5).to_a, label: "Combien d'étoiles ?" %>
        <%= f.input :comment, as: :text, label_html: { class: 'subtitle' }%>
      </div>

      <%# <%= link_to expo_reviews_path(current_user, @expo), data: {turbo_method: "post"} do%>
         <%# <p>Ajouter un commentaire</p>
      <% end %>

      <div class="modal-footer">
        <%= f.submit class: "action-button", value: "Valider", data: { bs_dismiss:"modal"} %>
        <%# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button> %>
      </div>
    </div>
  </div>
</div>
<% end %>